[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings for dependencies
remappings = [
    "@openzeppelin-v5/contracts/=lib/protocol-monorepo/lib/openzeppelin-contracts/contracts/",
    "protocol-monorepo/=lib/protocol-monorepo/packages/ethereum-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
